
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TextoGeneral = 21;
  public static final int PuntoComa = 9;
  public static final int Coma = 32;
  public static final int SignoMulti = 8;
  public static final int InicioTitle = 12;
  public static final int Enlace = 36;
  public static final int Error = 42;
  public static final int FinLi = 34;
  public static final int FinImg = 39;
  public static final int FinHead = 14;
  public static final int InicioLi = 33;
  public static final int Digito = 3;
  public static final int InicioHead = 11;
  public static final int InicioTextoB = 28;
  public static final int SalidaTexto = 30;
  public static final int EOF = 0;
  public static final int DosPuntos = 7;
  public static final int error = 1;
  public static final int FinList = 35;
  public static final int SignoIgual = 19;
  public static final int Texto = 23;
  public static final int FinBody = 40;
  public static final int FinTr = 26;
  public static final int URL = 22;
  public static final int InicioList = 31;
  public static final int SignoMas = 5;
  public static final int InicioBody = 15;
  public static final int Correo = 38;
  public static final int FinHtml = 41;
  public static final int FinTable = 27;
  public static final int ParC = 24;
  public static final int FinTh = 25;
  public static final int ParA = 20;
  public static final int InicioHtml = 2;
  public static final int InicioTr = 17;
  public static final int InicioImg = 37;
  public static final int SignoMenos = 6;
  public static final int InicioTh = 18;
  public static final int FinTitle = 13;
  public static final int FinTextoB = 29;
  public static final int InicioTable = 16;
  public static final int NDecimal = 4;
  public static final int Comillas = 10;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "InicioHtml",
  "Digito",
  "NDecimal",
  "SignoMas",
  "SignoMenos",
  "DosPuntos",
  "SignoMulti",
  "PuntoComa",
  "Comillas",
  "InicioHead",
  "InicioTitle",
  "FinTitle",
  "FinHead",
  "InicioBody",
  "InicioTable",
  "InicioTr",
  "InicioTh",
  "SignoIgual",
  "ParA",
  "TextoGeneral",
  "URL",
  "Texto",
  "ParC",
  "FinTh",
  "FinTr",
  "FinTable",
  "InicioTextoB",
  "FinTextoB",
  "SalidaTexto",
  "InicioList",
  "Coma",
  "InicioLi",
  "FinLi",
  "FinList",
  "Enlace",
  "InicioImg",
  "Correo",
  "FinImg",
  "FinBody",
  "FinHtml",
  "Error"
  };
}

